# Generated by Django 3.2 on 2021-04-29 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='Type',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='Deliver',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='quote',
            name='Take',
            field=models.IntegerField(max_length=128),
        ),
    ]
