# Generated by Django 3.2 on 2021-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210429_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='Deliver',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='quote',
            name='Take',
            field=models.CharField(max_length=128),
        ),
    ]
